[FEATURE]:Searchbar added in blog page
amupedia2021/Project-Amupedia pull request #509
Opened 2023-07-13 15:45 UTC by BhartiNagpure

## Description
#489 Searchbar added
I am added search bar in Blog page to search particular blog which user want.

## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [x] The app is working correctly after applying the changes.
- [x] The app is responsive and displays properly on different screen sizes and devices.
- [x] The changes are thoroughly documented in the appropriate files or documentation sections.
- [x] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [x] I have tested the changes locally and ensured that the app is functioning as expected.
- [x] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [x] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [x] I have followed the coding conventions and style guidelines defined in the project.
- [x] I have run the automated tests and all of them pass.
- [x] I have considered the performance implications of the changes made.
- [x] I have considered the security implications of the changes made.
- [x] I have checked for any potential regressions or side effects caused by the changes.
- [x] I have performed a self-review of my code.
- [x] Starred the repository.
- [x] Added My Name to the Contributor's List.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)
![Screenshot 2023-07-13 211310](https://github.com/amupedia2021/Project-Amupedia/assets/104631882/bf406efb-526e-4ccb-a617-5fc2f11fb67c)

## Additional Notes(Optional)

## Related Issues
#489 Feature searchbar added in blog

## Reviewers

Please tag the relevant team members or reviewers who should review this pull request.

2023-07-13 15:47 UTC, BhartiNagpure commented
@Harshil-Jani  please review my PR .

2023-07-13 17:47 UTC, Harshil-Jani commented
@BhartiNagpure I tried searching but it returns no blog for me. Can you please re-check ?

2023-07-13 17:49 UTC, Harshil-Jani requested changes

2023-07-13 17:49 UTC, Harshil-Jani commented on components/Blogs/BlogCard.js
> +
Please remove extra whitespaces.

2023-07-13 17:49 UTC, Harshil-Jani commented on components/Blogs/BlogCard.js
> +
Please remove extra whitespaces.

2023-07-13 17:49 UTC, Harshil-Jani commented on components/Blogs/BlogCard.js
> +
Please remove extra whitespaces.

2023-07-13 17:49 UTC, Harshil-Jani commented on pages/blog/index.js
> +
Please remove extra whitespaces.

2023-07-13 17:49 UTC, Harshil-Jani commented on pages/blog/index.js
> +   console.log(blogData.filter(blog => blog.title.includes("SQ")))
Remove console.log statement.

2023-07-13 17:49 UTC, Harshil-Jani commented on pages/blog/index.js
> +
Please remove extra whitespaces.

2023-07-13 17:49 UTC, Harshil-Jani commented on styles/Search.module.css
> +    }
Add new line at EOF

2023-07-13 17:49 UTC, Harshil-Jani commented on styles/scss/blog.module.scss
> +  }
New line at EOF

2023-07-14 08:27 UTC, Harshil-Jani commented
@BhartiNagpure Functionality wise the search bar is not working. Can you please look into it ?

2023-07-14 08:28 UTC, BhartiNagpure commented
> @BhartiNagpure Functionality wise the search bar is not working. Can you please look into it ?

from my side it is work also I check the deployment it work properly

2023-07-14 08:31 UTC, BhartiNagpure commented
![Screenshot 2023-07-14 135951](https://github.com/amupedia2021/Project-Amupedia/assets/104631882/3d68e749-18ac-4e92-b348-369648760a7b)
![Screenshot 2023-07-14 140008](https://github.com/amupedia2021/Project-Amupedia/assets/104631882/9f837333-8db3-4936-9f7b-a9920eb6ce76)

This is work in deployment.

2023-07-14 08:34 UTC, Harshil-Jani commented
I see. I was trying to search with `How`
![image](https://github.com/amupedia2021/Project-Amupedia/assets/79367883/3889eefa-c343-4d68-a025-d633b0acbfb6)

2023-07-14 08:37 UTC, Harshil-Jani commented
For example there is an article titled `Learn serverless on AWS step-by-step - SQL with Aurora` and I would want to search that. If I just remember the keyword `SQL` and try to search it. I do expect in return the article to show up.
![image](https://github.com/amupedia2021/Project-Amupedia/assets/79367883/046a8a5e-7b2e-46c1-9fb5-aa3da6eeac3a)

2023-07-14 08:37 UTC, BhartiNagpure commented
> I see. I was trying to search with `How` ![image](https://user-images.githubusercontent.com/79367883/253519219-3889eefa-c343-4d68-a025-d633b0acbfb6.png)

for how it is also work
![Screenshot 2023-07-14 140716](https://github.com/amupedia2021/Project-Amupedia/assets/104631882/85e46a51-8f98-47e1-80b3-d7e64503077b)

2023-07-14 08:39 UTC, BhartiNagpure commented
@Harshil-Jani how is present in above four card and you search it not suffle but you scroll down last card is remove as it not contain how.

2023-07-14 08:44 UTC, BhartiNagpure commented
> I see. I was trying to search with `How` ![image](https://user-images.githubusercontent.com/79367883/253519219-3889eefa-c343-4d68-a025-d633b0acbfb6.png)

I get it, this is because you are trying to search starting with capital letter.

2023-07-14 08:46 UTC, BhartiNagpure commented
@Harshil-Jani you may check now it works properly for capital letter also.

2023-07-14 08:50 UTC, Harshil-Jani requested changes
Great work @BhartiNagpure . Now the search works perfect. Can you please do some minor changes as commented and also please do format the code so it looks readable.

2023-07-14 08:50 UTC, Harshil-Jani commented on pages/blog/index.js
> +   }
Please remove this function `searchQueryHandler` since it is empty.

2023-07-14 08:52 UTC, BhartiNagpure commented
> Great work @BhartiNagpure . Now the search works perfect. Can you please do some minor changes as commented and also please do format the code so it looks readable.

sure

2023-07-14 08:57 UTC, BhartiNagpure commented
@Harshil-Jani  work done please check it.

2023-07-14 09:01 UTC, Harshil-Jani commented
Thanks a lot @BhartiNagpure.

2023-07-14 09:02 UTC, Harshil-Jani approved these changes

2023-07-14 09:14 UTC, merged

2023-07-14 14:16 UTC, BhartiNagpure commented
@Harshil-Jani you are not added any level , I am not getting points.

2023-07-14 18:26 UTC, Harshil-Jani commented
Added @BhartiNagpure