Add files via upload
amupedia2021/Project-Amupedia pull request #542
Opened 2023-07-17 11:17 UTC by SnigdhaP2022

## Created folders for B.com and B.Sc courses and added materials related to it 
This closes ISSUE #478 
Please provide a brief description of the changes introduced in this pull request. Explain the problem you are solving or the feature you are adding.
I have created folders for other courses and styled them according to the website's needs and specifications alignment. I have also related materials to the branches I have mentioned according to the course.
## Pull Request Checklist

Please make sure that your PR meets the following requirements:

- [✅ ] The app is working correctly after applying the changes.
- [ ✅] The app is responsive and displays properly on different screen sizes and devices.
- [✅ ] The changes are thoroughly documented in the appropriate files or documentation sections.
- [ ✅] The coding conventions and style guidelines are followed consistently.

## Checklist

Please check all applicable boxes and provide any additional information if needed.

- [✅ ] I have tested the changes locally and ensured that the app is functioning as expected.
- [ ✅] I have verified that the app is responsive and looks good on various screen sizes and devices.
- [ ✅] I have reviewed the documentation and ensured that it accurately reflects the changes made.
- [ ✅] I have followed the coding conventions and style guidelines defined in the project.
- [✅ ] I have run the automated tests and all of them pass.
- [ ✅] I have considered the performance implications of the changes made.
- [✅ ] I have considered the security implications of the changes made.
- [✅ ] I have checked for any potential regressions or side effects caused by the changes.
- [✅ ] I have performed a self-review of my code.
- [✅ ] Starred the repository.
- [ ] Added My Name to the Contributor's List.
- [ ✅] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [✅ ] I ran the app and tested it locally to verify that it works as expected.

# Screenshots - If Any (Optional)
<img width="1438" alt="Screenshot 2023-07-17 at 4 43 36 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/102572480/9e02cb40-5fef-4149-b0fd-ff3885492de4">

<img width="1438" alt="Screenshot 2023-07-17 at 4 44 02 PM" src="https://github.com/amupedia2021/Project-Amupedia/assets/102572480/cc95bfe8-09f9-4719-8938-43a1cda2b475">

## Additional Notes(Optional)
I have contributed under GSSOC'23. I am happy to be a part of this project. Thank you for the opportunity. Excited to see myself in the contribution list after merging.
Please provide any additional information or context that may be helpful for reviewing the pull request.

## Related Issues

Please list any related issues or pull requests that are associated with this pull request.

## Reviewers
@Harshil-Jani  Kindly, review this PR

Please tag the relevant team members or reviewers who should review this pull request.

2023-07-17 11:39 UTC, SnigdhaP2022 commented
@Harshil-Jani  Kindly, review this PR. Thank you for making me part of this project.

2023-07-17 14:59 UTC, anmode requested changes
can these jpg files convert into webp?? actually jpg take lot of size

2023-07-17 15:02 UTC, SnigdhaP2022 commented
Yeah, I'll try to make the necessary changes and commit the files.

2023-07-17 17:10 UTC, SnigdhaP2022 commented
@anmode  I have made requested changes by changing images jpg to webp. Kindly, review this and merge the files

2023-07-17 22:01 UTC, Harshil-Jani commented
@SnigdhaP2022 Thanks for contributing to other courses. This helps us a lot. I would like to see a small enhancement into this and that is when from the Navbar you select on `B.Comm` or `BSc` then it should open up page just like it opens up in case of `B.Tech`. Can you please make this possible and we can merge this to help students from other streams ? 🎉

2023-07-17 22:04 UTC, Harshil-Jani requested changes

2023-07-17 22:04 UTC, Harshil-Jani commented on pages/courses/bcom/index.js
> +      {/* <!-- content of b.tech section  --> */}
update comment to change it for `b.com`

2023-07-17 22:04 UTC, Harshil-Jani commented on pages/courses/bsc/index.js
> +      {/* <!-- content of b.tech section  --> */}
ditto here

2023-07-18 03:42 UTC, SnigdhaP2022 commented on pages/courses/bcom/index.js
> +      {/* <!-- content of b.tech section  --> */}
Updated

2023-07-18 03:43 UTC, SnigdhaP2022 commented on pages/courses/bsc/index.js
> +      {/* <!-- content of b.tech section  --> */}
Updated

2023-07-18 03:44 UTC, SnigdhaP2022 commented
@Harshil-Jani  @anmode Requested changes have been updated. Kindly, review the file and merge the PR 🎉

2023-07-18 11:06 UTC, Harshil-Jani commented
Thankyou for such valuable contribution @SnigdhaP2022 🎉

2023-07-18 11:06 UTC, Harshil-Jani approved these changes

2023-07-18 11:06 UTC, merged

2023-07-18 11:34 UTC, SnigdhaP2022 commented
@Harshil-Jani  requesting you to kindly add level label for the PR. Otherwise it won't consider for GSSOC'23 Contribution.